/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Container: typeof import('./src/components/subcontainer/src/container.vue')['default']
    Countdown: typeof import('./src/components/countdown/Countdown/Countdown.vue')['default']
    CustomPage: typeof import('./src/components/custom-page/src/custom-page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Subcontainer: typeof import('./src/components/subcontainer/src/subcontainer.vue')['default']
  }
}
